image: maven:latest

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn clean verify

  after_script:
    - echo "Preparing serenity report"
    - rm -rf /var/lib/apt/lists/*
    - apt-get update
    - apt-cache gencaches
    - apt-get install -y zip unzip
    - zip -r serenity_report.zip ./target/site/serenity
    - echo "Serenity report ready, you can download it from artifacts section"

  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - ./serenity_report.zip